# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy package files first for better caching
COPY package*.json ./

# Install dependencies without running any scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose port 8899 (as per default configuration)
EXPOSE 8899

# Set the default command to run the MCP server
CMD ["node", "dist/index.js", "--host", "0.0.0.0", "--port", "8899"]
